db:
  container_name: "couchbase4"
  build: .
  # image: couchbase/server:community
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210
  environment:
    # Can be a comma-separated list, possible values being combinations of gamesim-sample, beer-sample, travel-sample
    - SAMPLE_BUCKETS=travel-sample
  